### PR TITLE
Initial integration of Vimeo API v3

### PR DESCRIPTION
**Pull request by jcohlmeyer**

### CODE REVIEW

**Comment by jcohlmeyer** [comment]
From my test this returned lower quality thumbnails as an inconsistent array. It also requires an API key. I do not see the benefit? @jeffwhitfield do you think there is a benefit to V3 API?

**Comment by jeffwhitfield** [comment]
I find the current implementation of the API to be lacking. The highest resolution returned isn't really the highest available. To work around this for one of my projects, I had to implement the V3 API. What I have there isn't perfect but gave me what I needed to finish the project. 

That said, I think it would be good to explore this and perhaps find a way to return an array of available image sizes that can be parsed easily. What I think would be cool is a way to return the highest available image up to a certain size. So, for instance, I could tell it to give me the highest image up to 1200 pixels wide. Basically, we need to find a way to save all available images in the array returned. Then, we need to create methods that allow for tags with some basic filtering.

**Comment by jeffwhitfield** [comment]
And, no, what I have is in no way ready to be integrated yet. :P

**Comment by jcohlmeyer** [comment]
Yes, thank you for investigating this. There area also higher resolution images available for YouTube that are not returned via their most recent API, however the urls are easy to figure out based on the ID of the video.

I do think I should have put the thumbnails in an array instead of storing the three different sizes as I do now, that would give us the option to store additional information with them, such as size.

For example:
```
thumbnails:
  -
    url: https://vimeo.com/thumbnail
    width: 1200
    height: 640
  -
    url: https://vimeo.com/other_thumbnail
    width: 640
    height: 480
```

I was also thinking about an option that would allow saving these images an assets folder so that glide manipulations would be cached.

Would you like to work on this a bit more?

Plus thanks again for looking into the V3 API.

**Comment by jeffwhitfield** [comment]
I'll definitely be looking more into this. I think if we simply save the URL's into an array then that'll do. Don't think it's a good idea to cache the images though. One of the things I found with using Vimeo's images is that they act as a good CDN. Performance on pages where I'm listing multiple images goes up when loading directly from Vimeo. So, no, I wouldn't cache the images. Just need an easy way to store an array of image URL's as well as a simple way to filter them based on size.

**Comment by jcohlmeyer** [comment]
I was more thinking of the caching the images for doing glide manipulations, right now glide manipulations done to remote image have to be done with every page request. Storing the thumbnails locally for better glide cropping would be a separate task though, and an optional setting.

**Comment by jeffwhitfield** [comment]
Ah, I see what you’re saying! Very good point. As long as it’s an optional setting, I think we’ll be alright. :)

**Pull request closed without merging**
